<?php
/*
    Dack's DND Tools - core/slider.php
    ==================================
    This file contains the HTML structure for the hero slider, which is displayed
    on the homepage. The slider's functionality is powered by js/main.js.
*/
?>

<!-- 
    SECTION 1: SLIDER CONTAINER
    ===========================
    This is the main container for the entire slider component. It sets the
    slider's dimensions and positions its navigation elements.
-->
<div id="hero-slider" class="relative w-full h-96 md:h-[500px] overflow-hidden shadow-lg">
    
    <!-- 
        SECTION 2: SLIDES WRAPPER
        =========================
        This div holds all the individual slide elements.
    -->
    <div class="relative h-full">
        
        <!-- Slide 1: Character Sheet -->
        <div class="hero-slide absolute w-full h-full transition-opacity duration-1000 ease-in-out opacity-0">
            <img src="https://wallpapers.com/images/featured/fantasy-05e34f7bfyhne5vg.jpg" class="w-full h-full object-cover" alt="Fantasy Map">
            <div class="absolute inset-0 bg-black/50 flex items-center justify-center">
                <a href="<?php echo BASE_URL; ?>sheet" class="text-center p-4">
                    <h2 class="text-4xl md:text-6xl text-white font-bold title-font">Forge Your Legend</h2>
                    <p class="text-lg md:text-xl text-white/90 mt-2">Create and manage your characters with a powerful digital sheet.</p>
                </a>
            </div>
        </div>
        
        <!-- Slide 2: Dice Roller -->
        <div class="hero-slide absolute w-full h-full transition-opacity duration-1000 ease-in-out opacity-0">
            <img src="https://i.imgur.com/ynV0Us0.jpeg" class="w-full h-full object-cover" alt="Dice on a table">
             <div class="absolute inset-0 bg-black/50 flex items-center justify-center">
                <a href="<?php echo BASE_URL; ?>dice" class="text-center p-4">
                    <h2 class="text-4xl md:text-6xl text-white font-bold title-font">Let Fate Decide</h2>
                    <p class="text-lg md:text-xl text-white/90 mt-2">A versatile dice roller for every situation.</p>
                </a>
            </div>
        </div>
        
        <!-- Slide 3: Compendium -->
        <div class="hero-slide absolute w-full h-full transition-opacity duration-1000 ease-in-out opacity-0">
            <img src="https://wallpapers.com/images/featured/fantasy-landscape-awufx83svt5lunf3.jpg" class="w-full h-full object-cover" alt="An old book">
             <div class="absolute inset-0 bg-black/50 flex items-center justify-center">
                <a href="<?php echo BASE_URL; ?>compendium" class="text-center p-4">
                    <h2 class="text-4xl md:text-6xl text-white font-bold title-font">Unlock Ancient Lore</h2>
                    <p class="text-lg md:text-xl text-white/90 mt-2">Instantly search the entire 5e SRD Compendium.</p>
                </a>
            </div>
        </div>
    </div>
    
    <!-- 
        SECTION 3: SLIDER NAVIGATION CONTROLS
        =====================================
        These elements allow the user to manually control the slider.
    -->
    
    <!-- Previous/Next Arrow Buttons -->
    <button id="slider-prev" class="absolute top-1/2 left-4 -translate-y-1/2 bg-black/50 text-white p-3 rounded-full hover:bg-black/75 transition-colors">
        <i class="fas fa-chevron-left"></i>
    </button>
    <button id="slider-next" class="absolute top-1/2 right-4 -translate-y-1/2 bg-black/50 text-white p-3 rounded-full hover:bg-black/75 transition-colors">
        <i class="fas fa-chevron-right"></i>
    </button>
    
    <!-- Dot Indicators for each slide -->
    <div id="slider-dots" class="absolute bottom-4 left-1/2 -translate-x-1/2 flex space-x-2">
        <!-- Dots are dynamically generated by JavaScript -->
    </div>
</div>
